# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "categories", :force => true do |t|
    t.column "name",           :string
    t.column "contacts_count", :integer, :default => 0
  end

  create_table "categories_zones", :id => false, :force => true do |t|
    t.column "category_id", :integer
    t.column "zone_id",     :integer
  end

  create_table "contacts", :force => true do |t|
    t.column "name",         :string
    t.column "email",        :string
    t.column "tester",       :boolean
    t.column "active",       :boolean
    t.column "category_id",  :integer
    t.column "confirmation", :string
  end

  create_table "eflyers", :force => true do |t|
    t.column "costumer",     :string
    t.column "name",         :string
    t.column "subject",      :string
    t.column "from",         :string
    t.column "link",         :string
    t.column "email",        :string
    t.column "body",         :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "hold",         :boolean
    t.column "delivered_to", :integer,  :default => 0
    t.column "format",       :integer,  :default => 1
    t.column "owner_id",     :integer
    t.column "category_id",  :integer
    t.column "plain_text",   :text
  end

  create_table "emails", :force => true do |t|
    t.column "from",              :string
    t.column "to",                :string
    t.column "last_send_attempt", :integer,  :default => 0
    t.column "mail",              :text
    t.column "created_on",        :datetime
    t.column "eflyer_id",         :integer
  end

  create_table "owners", :force => true do |t|
    t.column "name", :string
  end

  create_table "photos", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "eflyer_id",    :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "salt",  :string
    t.column "hass",  :string
  end

  create_table "zones", :force => true do |t|
    t.column "name", :string
  end

end
